config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about',to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/signup', to: 'users#new'
  get '/personal', to: 'users#show'
  resources :users
  get '/users/:id/activate', to: 'users#activate'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_create :set_activation_token
  attr_accessor :remember_token

  validates :name, presence: true, length: { maximum: 50}
  validates :email,
    presence: true, length: { in: 3..255 },
    format: { with: ApplicationHelper::VALID_EMAIL_REGEXP },
    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }, allow_nil: true

  default_scope { where(active: true) }

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def session_token
    remember_digest || remember
  end

  def forget
    self.remember_token = nil
    update_attribute(:remember_digest, nil)
  end

  def authenticated_with_token?(token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(token)
  end

  def is_god?
    role == 'admin'
  end

  private
  def set_activation_token
    token = User.digest(User.new_token)
    self.activation_token = token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  before_action :set_current_user
  protect_from_forgery with: :null_session

  def new
    if @current_user
      flash[:warning] = 'You are already logged in!'
      redirect_to @current_user
    end
  end

  def create
    if @current_user
      flash[:warning] = 'You are already logged in!'
      return redirect_to @current_user
    end

    @user = User.unscoped.find_by(email: params[:session][:email])

    if @user&.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      params[:session][:remember_me] == '1' ? remember_session(@user) :
                                              forget_session(@user)
      log_in(@user)
      flash[:success] = 'You are logged in!'
      return redirect_to forwarding_url || @user
    elsif @user.nil?
      flash.now[:danger] = 'Email not found!'
    else
      flash.now[:danger] = 'Incorrect password!'
    end
    render :new
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path, flash: { success: "You have successfully logged out." }
  end

  private
  def set_current_user
    @current_user = current_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contacts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :find_user, except: [:new, :create]
  before_action :logged_in, only: [:index, :edit, :update, :destroy]
  before_action :check_activate, except: [:new, :create, :show, :activate]
  before_action :check_authorisation, only: [:edit, :update]
  before_action :check_admin, only: [:destroy]

  def index
    @user = current_user
    @users = User.paginate(page: params[:page]).order(:id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.active = false
    if @user.save
      reset_session
      # User::UserActivatorService.call(@user)
      remember_session @user
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      flash[:danger] = "Try again!"
      render :new, status: :unprocessable_entity
    end
  end

  def show  
    return redirect_to current_user, flash: {
      warning: "Your account isn't activated yet"
    } if !current_user?(@user) && !current_user.active?

    redirect_to root_path, flash: { warning: 'User not found!' } if @user.nil?
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user
      @user.destroy
      flash[:success] = "User was deleted"
      redirect_to users_path
    else
      flash.now[:danger] = "User not found"
    end
  end

  def activate
    if @user.active?
      flash[:notice] = "Your account is active already"
    elsif params[:token] && @user.activation_token != params[:token]
      flash[:danger] = "Incorrect activation link!"
    else
      @user.active = true
      if @user.save
        flash[:success] = "Your account was activated"
        @user.update_attribute(:activation_token, nil)
      else
        flash[:danger] = "Error! Please connect with administrator!"
      end
    end
    redirect_to @user
  end


  private
  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation
    )
  end

  def find_user
    @user = User.unscoped.find_by(id: params[:id])
  end

  def check_activate
    redirect_to current_user, flash: {
      warning: "Your account isn't activated yet"
    } unless current_user&.active?
  end

  def logged_in
    unless logged_in?
      flash[:warning] = "Please log in to access this page"
      store_location
      redirect_to "#{login_path}?from=#{params[:action]}_user"#, params: { from: 'edit_user'}
    end
  end

  def check_authorisation
    unless current_user?(@user) || current_user.is_god?
      flash[:warning] = "You don't have permissions to this action"
      redirect_to current_user
    end
  end

  def check_admin
    unless current_user.is_god?
      flash[:warning] = "You don't have permissions to this action"
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  VALID_EMAIL_REGEXP = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    unless page_title.empty?
      base_title = page_title + ' | ' + base_title
    end
    base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    session[:session_token] = user.session_token
  end

  def remember_session(user)
    user.remember
    cookies.encrypted.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget_session(user)
    cookies.delete :user_id
    cookies.delete :remember_token
    user.forget unless user.nil?
  end

  def current_user
    if session[:user_id]
      user = User.unscoped.find_by(id: session[:user_id])
      if user&.session_token == session[:session_token]
        user
      end
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.unscoped.find_by(id: user_id)
      if user&.authenticated_with_token?(cookies[:remember_token])
        log_in(user)
        user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    forget_session(@current_user)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_img_tag(user, size: 80)
    gr_id = Digest::MD5::hexdigest user.email
    image_tag("https://secure.gravatar.com/avatar/#{gr_id}?s=#{size}",
      alt: user.name, class: 'gravatar')
  end

  def pagination(page_number = 1)
    page_number = 1 if page_number.nil?
    User.where(id: ((page_number.to_i - 1)*3 + 1)..page_number.to_i*3)
  end

  def page_number_plus
    n = params[:page].nil? ? 1 : params[:page].to_i

    if 3*n + 1 > User.count
      0
    else
      n + 1
    end
  end

  def page_number_minus
    params[:page].nil? ? 0 : params[:page].to_i - 1
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contacts_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class=container>
    <%= link_to "sample app", root_path, id: 'logo' =%>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
          id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path =%></li>
          <li><%= link_to "Help", help_path =%></li>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Log out', logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' =%>
    <%= render 'layouts/shim' =%>
  </head>

  <body>
    <%= render 'layouts/header' =%>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' =%>
    </div>
    <%= debug(params) if Rails.env.development? =%>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/shared/_user_form.html.erb
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name =%>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email =%>
      <%= f.email_field :email, class: 'form-control' =%>

      <%= f.label :password =%>
      <%= f.password_field :password, class: 'form-control' =%>

      <%= f.label :confirmation =%>
      <%= f.password_field :password_confirmation, class: 'form-control' =%>

      <%= f.submit yield(:button_text), class: "btn btn-primary" =%>
    <% end %>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a>, part of the
  <a href="https://www.learnenough.com/">Learn Enough</a> family of
  tutorials, is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="https://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/contacts.html.erb
<% provide :title, 'Contacts' %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide :title, 'Help' %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
  <br>
</p>

app/views/static_pages/home.html.erb
<% provide :title, 'Home' %>
<div class="center jumbotron">
  <h1>Sample App</h1>
  <p>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-log btn-primary" =%>
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), 
    "https://rubyonrails.org/" =%>
<%#= image_tag "kitten.jpg" =%>

app/views/users/_user.html.erb
<li>
  <%= gravatar_img_tag user, size: 50 %>
  <%= link_to user.name, user %>
  <% if @user != user && @user.is_god? %>
  | <%= link_to "delete", user, method: :delete, data: {confirm: "Are you sure?"}   %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit profile") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/user_form' %>

    <div class="gravatar-edit">
      <%= gravatar_img_tag @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/user_form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<% if @user.active? %>
  <div class='row'>
    <aside class='col-md-4'>
      <section class='user_info'>
        <h1>
          <%= @user.name =%>
          <%= gravatar_img_tag(@user, {size: 200}) =%>
        </h1>
        <div class="email"><%= @user.email if logged_in?%></h1>
      </section>
    </aside>
  </div>
<% else %>
  <h1>Hello, <%= @user.name %>!</h1>
  <h2>Your account isn't activated yet. Please check <%= @user.email %> and click by our link from the letter</h2>
<% end %>